# Generated by Django 4.2.7 on 2023-12-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='country',
        ),
    ]
