# Generated by Django 4.2.7 on 2023-12-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
    ]
