# Generated by Django 4.2.7 on 2023-12-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_remove_country_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
