# Generated by Django 4.2.7 on 2023-12-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='Continent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.continent'),
        ),
    ]
