# Generated by Django 4.2.7 on 2023-12-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_city_country_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Continent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.continent'),
        ),
    ]
