# Generated by Django 4.2.7 on 2023-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_rename_country_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
