# Generated by Django 4.2.7 on 2023-12-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_hotelimage_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
    ]
