# Generated by Django 4.2.7 on 2023-12-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0012_remove_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city', verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.country', verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=132, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Komentář'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Změněno'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.continent', verbose_name='Kontinent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=132, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotels_of_cities', to='viewer.city', verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=132, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1 hvězdička'), (2, '2 hvězdičky'), (3, '3 hvězdičky'), (4, '4 hvězdičky'), (5, '5 hvězdiček')], default=0, verbose_name='Počet hvězdiček'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number_of_adults',
            field=models.IntegerField(default=0, verbose_name='Počet dospělých'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Počet dětí'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='special_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Zvláštní požadavky'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena celkem'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='travel_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.travelpackage', verbose_name='Cestovní balíček'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum příjezdu'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum odjezdu'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.mealplan', verbose_name='Strava'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za dítě'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za osobu'),
        ),
    ]
