# Generated by Django 4.2.7 on 2023-12-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_rename_price_per_person_travelpackage_base_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpackage',
            old_name='base_price',
            new_name='base_price_p_p',
        ),
        migrations.AddField(
            model_name='airport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za dopravu'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za stravu'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_with_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena s dopravou'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Celková cena za pobyt'),
        ),
    ]
