# Generated by Django 4.2.7 on 2023-12-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_rename_base_price_travelpackage_base_price_p_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=68, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=68, verbose_name='Příjmení')),
                ('birth_date', models.DateField(default=None, verbose_name='Datum narození')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='number_of_adults',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_with_transport',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='travel_package',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='base_price_p_p',
        ),
        migrations.AddField(
            model_name='hotel',
            name='booked_rooms',
            field=models.IntegerField(default=0, verbose_name='Rezervované pokoje'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_of_country', to='viewer.country', verbose_name='Stát'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='double_rooms',
            field=models.IntegerField(default=0, verbose_name='Dvoulůžkové pokoje'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='family_rooms',
            field=models.IntegerField(default=0, verbose_name='Rodinné pokoje'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='single_rooms',
            field=models.IntegerField(default=0, verbose_name='Jednolůžkové pokoje'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='suites',
            field=models.IntegerField(default=0, verbose_name='Apartmány'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(default=0, verbose_name='Celkový počet pokojů'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='number_of_adults',
            field=models.IntegerField(default=0, verbose_name='Počet dospělých'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Počet dětí'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='price_per_day_adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za osobu'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='price_per_day_children',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za dítě'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.travelpackage', verbose_name='Cena celkem'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_packages', to='viewer.mealplan', verbose_name='Strava'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='travelers',
            field=models.ManyToManyField(related_name='travelers_purchases', to='viewer.traveler', verbose_name='Cestující'),
        ),
    ]
