# Generated by Django 4.2.7 on 2023-12-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_traveler_remove_purchase_number_of_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_airport', to='viewer.airport', verbose_name='Letiště'),
        ),
    ]
