# Generated by Django 4.2.7 on 2024-01-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_hotel_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='price',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='departure_airport',
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena dopravy')),
                ('arrival_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_transportation', to='viewer.airport', verbose_name='Letiště příletu')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_transportation', to='viewer.airport', verbose_name='Letiště odletu')),
            ],
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportation', to='viewer.transportation', verbose_name='Doprava'),
        ),
    ]
