# Generated by Django 4.2.7 on 2024-01-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_remove_airport_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='country_of_continents', to='viewer.continent', verbose_name='Kontinent'),
        ),
    ]
