# Generated by Django 4.2.7 on 2024-01-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_remove_country_continent_country_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=132, null=True, verbose_name='Ostrov')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='viewer.country', verbose_name='Stát')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='island',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='viewer.island', verbose_name='Ostrov'),
        ),
    ]
