# Generated by Django 4.2.7 on 2024-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_remove_prices_price_adult_remove_prices_price_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price_double_room',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena za dvoulůžkový pokoj'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_family_room',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena za rodinný pokoj'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_single_room',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena za jednolůžkový pokoj'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_suite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena za apartmán'),
        ),
    ]
