# Generated by Django 4.2.7 on 2024-01-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_alter_prices_price_double_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='airport',
        ),
        migrations.AddField(
            model_name='hotel',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_transportation', to='viewer.transportation', verbose_name='Doprava'),
        ),
    ]
