# Generated by Django 4.2.7 on 2024-01-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_remove_hotel_airport_hotel_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='transportation',
        ),
        migrations.AddField(
            model_name='transportation',
            name='hotel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.hotel'),
        ),
    ]
