# Generated by Django 4.2.7 on 2024-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_remove_hotel_transportation_transportation_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='hotel',
        ),
    ]
