# Generated by Django 4.2.7 on 2024-01-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_remove_transportation_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='transportation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transportation_of_hotel', to='viewer.transportation', verbose_name='Doprava'),
        ),
    ]
