# Generated by Django 4.2.7 on 2024-01-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0028_hotel_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum příjezdu'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum odjezdu'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='hotel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_hotel', to='viewer.hotel'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='meal_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_packages', to='viewer.mealplan', verbose_name='Strava'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number_of_double_rooms',
            field=models.IntegerField(default=0, verbose_name='Počet dvoulůžkových pokojů'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number_of_family_rooms',
            field=models.IntegerField(default=0, verbose_name='Počet rodinných pokojů'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number_of_single_rooms',
            field=models.IntegerField(default=0, verbose_name='Počet jednolůžkových pokojů'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number_of_suites',
            field=models.IntegerField(default=0, verbose_name='Počet apartmánů'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transportation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_transportation', to='viewer.transportation', verbose_name='Doprava'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_customer', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena celkem'),
        ),
        migrations.DeleteModel(
            name='TravelPackage',
        ),
    ]
