# Generated by Django 4.2.7 on 2024-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_purchase_arrival_date_purchase_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='travelers',
        ),
        migrations.AddField(
            model_name='purchase',
            name='traveler',
            field=models.ManyToManyField(related_name='travelers_purchase', to='viewer.traveler', verbose_name='Cestující'),
        ),
    ]
