# Generated by Django 4.2.7 on 2024-01-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_hotel_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='suites',
            new_name='suite_rooms',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='number_of_double_rooms',
            new_name='double_rooms',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='number_of_family_rooms',
            new_name='family_rooms',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='number_of_single_rooms',
            new_name='single_rooms',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='number_of_suites',
            new_name='suite_rooms',
        ),
    ]
