# Generated by Django 4.2.7 on 2024-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_rename_suites_hotel_suite_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='travelers',
            field=models.IntegerField(default=1, verbose_name='Počet cestujících'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aktuální cena'),
        ),
    ]
