# Generated by Django 4.2.7 on 2024-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_hotel_travelers_purchase_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='current_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena celkem'),
        ),
    ]
