# Generated by Django 4.2.7 on 2024-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_remove_purchase_current_price_hotel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='travelers',
            field=models.IntegerField(default=1, verbose_name='Celkem cestujících'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='travelers',
            field=models.IntegerField(default=1, verbose_name='Celkem cestujících'),
        ),
    ]
