# Generated by Django 4.2.7 on 2024-01-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0039_alter_traveler_birth_date_alter_traveler_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='purchase',
        ),
    ]
