# Generated by Django 4.2.7 on 2024-01-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0040_remove_traveler_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='purchase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.purchase'),
        ),
    ]
