# Generated by Django 4.2.7 on 2024-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0042_remove_traveler_purchase_purchase_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='traveler',
        ),
        migrations.AddField(
            model_name='purchase',
            name='traveler',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='purchase_travelers', to='viewer.traveler'),
        ),
    ]
