# Generated by Django 4.2.7 on 2024-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0043_remove_purchase_traveler_purchase_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default=None, max_length=68, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default=None, max_length=68, verbose_name='Příjmení'),
        ),
    ]
