# Generated by Django 4.2.7 on 2024-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_alter_traveler_first_name_alter_traveler_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=68, null=True, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=68, null=True, verbose_name='Příjmení'),
        ),
    ]
