# Generated by Django 4.2.7 on 2024-01-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_alter_traveler_first_name_alter_traveler_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('single_rooms_available', models.IntegerField(default=0)),
                ('double_rooms_available', models.IntegerField(default=0)),
                ('family_rooms_available', models.IntegerField(default=0)),
                ('suite_rooms_available', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.hotel')),
            ],
        ),
    ]
