# Generated by Django 4.2.7 on 2024-01-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0046_roomavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('family', 'Family Room'), ('suite', 'Suite')], default='double', max_length=10),
        ),
    ]
