# Generated by Django 4.2.7 on 2024-01-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0049_alter_roomavailability_departure_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='double_rooms',
            new_name='double_rooms_available',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='family_rooms',
            new_name='family_rooms_available',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='single_rooms',
            new_name='single_rooms_available',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='suite_rooms',
            new_name='suite_rooms_available',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='double_rooms_available',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='family_rooms_available',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='single_rooms_available',
        ),
        migrations.RemoveField(
            model_name='roomavailability',
            name='suite_rooms_available',
        ),
    ]
