# Generated by Django 4.2.7 on 2024-01-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0050_rename_double_rooms_hotel_double_rooms_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='double_rooms_available',
            new_name='double_rooms',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='family_rooms_available',
            new_name='family_rooms',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='single_rooms_available',
            new_name='single_rooms',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='suite_rooms_available',
            new_name='suite_rooms',
        ),
        migrations.DeleteModel(
            name='RoomAvailability',
        ),
    ]
