# Generated by Django 4.2.7 on 2024-02-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0051_rename_double_rooms_available_hotel_double_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.country', verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='city',
            name='island',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='viewer.island', verbose_name='Ostrov'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.continent', verbose_name='Kontinent'),
        ),
        migrations.AlterField(
            model_name='island',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='viewer.country', verbose_name='Stát'),
        ),
    ]
