# Generated by Django 4.2.7 on 2023-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jméno',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='příjmení',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
