# Generated by Django 4.2.7 on 2023-12-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_jméno_profile_příjmení'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jméno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='příjmení',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='Země'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulice'),
        ),
    ]
