# Generated by Django 4.2.7 on 2024-01-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_jméno_remove_profile_příjmení_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='description',
        ),
    ]
